# Problem Statement: **Welcome to AI Town!**

### You’ve been hired as an AI engineer in **AI Town**, a futuristic city powered by artificial intelligence. Your job is to use PyTorch to solve foundational challenges that AI Town faces. Each task requires you to demonstrate your expertise with PyTorch basics.



---



Imports and CUDA

In [ ]:
import torch

# Check if CUDA (GPU) is available
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")


Using device: cuda




---



**Task1: Inventory Management**

AI Town’s warehouse uses sensors to record the inventory of 5 items every day. Each day’s data is represented as a list of integers (number of units).

In [ ]:
#1 Create a PyTorch Tensor from the following inventory data
inventory = [[12, 15, 10, 0, 5],
             [10, 8, 7, 5, 4],
             [20, 10, 15, 5, 2]]

inventory_tensor = torch.tensor(inventory)
print(inventory_tensor)

tensor([[12, 15, 10,  0,  5],
        [10,  8,  7,  5,  4],
        [20, 10, 15,  5,  2]])


In [ ]:
#2 Find the total inventory for each item across all days
total_inventory = inventory_tensor.sum(dim=0) # sum across rows
print(total_inventory)

tensor([42, 33, 32, 10, 11])


In [ ]:
#3 Find the average inventory per day
'''mean() function in PyTorch requires the tensor to be a floating-point type (e.g., float32 or float64)
'''
average_inventory = inventory_tensor.float().mean(dim=1) # mean across columns
print(average_inventory)

tensor([ 8.4000,  6.8000, 10.4000])


OR

In [ ]:
average_inventory = inventory_tensor.mean(dim=1, dtype=torch.float32) # mean across columns
print(average_inventory)

tensor([ 8.4000,  6.8000, 10.4000])


**KEY INSIGHTS**

* dim=0 means summing across rows (column-wise), while dim=1 sums across columns (row-wise).
* Tensor operations are efficient and avoid explicit loops.



---



**Task2: Monitoring Vehicle Flow**

AI Town uses a sensor to monitor the number of vehicles passing through two main roads every hour. The data for one day (24 hours) is represented as two
1×24 tensors.

In [ ]:
#1 Simulate this data using PyTorch's Random Functions
road1 = torch.randint(50, 200, (24,))
road2 = torch.randint(50, 200, (24,))
print(road1)
print(road2)

tensor([194,  56, 117,  86, 173,  55, 108,  55,  83, 133, 119,  68, 138, 140,
        186,  67, 130,  82, 136, 122, 141, 161,  94, 133])
tensor([ 91,  89,  54, 120,  56,  64, 176, 115, 150,  74, 175, 160, 107, 149,
         96,  87,  62, 186, 107, 163, 185, 166, 177, 148])


In [ ]:
#2 Write the function to calculate the total vehicle flow for each road across the entire day
total_flow_road1 = road1.sum() # total for road1
total_flow_road2 = road2.sum() # total for road2
print(total_flow_road1)
print(total_flow_road2)

tensor(2777)
tensor(2957)


In [ ]:
#3 Write the function to calculate the total vehicle flow for each hour across both roads
total_flow_hourly  = road1 + road2
print()


tensor([285, 145, 171, 206, 229, 119, 284, 170, 233, 207, 294, 228, 245, 289,
        282, 154, 192, 268, 243, 285, 326, 327, 271, 281])


**KEY INSIGHTS**

* Use torch.randint() for simulating random data in a specific range.
* Element-wise addition works seamlessly on tensors of the same shape.

---



**Task3: Fitness Matrix**

The AI Gym tracks members’ fitness scores using a 3×3 matrix for *strength*, *stamina*, and f*lexibility*. Each row represents a different member, and each column represents a specific metric.

In [ ]:
#1 Create a 3*3 tensor matrix and multiply the scores of each member by a weight factor: [0.8, 1.2, 1.5]
fitness = torch.tensor([[10, 20, 30],
                        [40, 50, 60],
                        [70, 80, 90]])
weights = torch.tensor([0.8, 1.2, 1.5])
weighted_fitness = weights * fitness
print(weighted_fitness)

tensor([[  8.0000,  24.0000,  45.0000],
        [ 32.0000,  60.0000,  90.0000],
        [ 56.0000,  96.0000, 135.0000]])


In [ ]:
#2 Find the row-wise and column-wise maximum scores
row_max = weighted_fitness.max(dim=1) # max for each row
col_max = weighted_fitness.max(dim=0) # max for each column
print(row_max)
print(col_max)

torch.return_types.max(
values=tensor([ 45.,  90., 135.]),
indices=tensor([2, 2, 2]))
torch.return_types.max(
values=tensor([ 56.,  96., 135.]),
indices=tensor([2, 2, 2]))


In [ ]:
#3 Transpose the fitness matrix and interpret it's new structure (shape)
transposed_fitness = fitness.t()
print(transposed_fitness)


tensor([[10, 40, 70],
        [20, 50, 80],
        [30, 60, 90]])


**KEY INSIGHTS**

Learn [Broadcasting](https://pytorch.org/docs/stable/notes/broadcasting.html) and do changes in 'weighted fitness', the output will remain the same



---



**Task4: Chain Rule in Action**

AI Lab is running experiments to understand the effect of temperature (
x) on a chemical reaction rate (y). The relationship is given as:
$y = 2x^3 + 5x^2 - 3x + 7$



In [ ]:
#1 Use PyTorch to compute 'y' for x = 4

# let's define x first
x = torch.tensor(4.0, requires_grad=True)

# now define y
y = 2*x**3 + 5*x**2 - 3*x + 7

print(y)


tensor(203., grad_fn=<AddBackward0>)


In [ ]:
#2 Calculate dy/dx (gradient) using PyTorch's autograd
y.backward(retain_graph = True)
gradient = x.grad

print(gradient)

tensor(133.)


**KEY INSIGHTS**

* If you need to call .backward() on the same graph multiple times, you need to specify retain_graph=True when calling .backward()
* *WHY*? because in PyTorch, the computational graph used for the operation is freed by default to save memory



---



**Task5: Camera Calibration**

AI Town’s surveillance cameras need to align their focus. You are given the following matrices for two cameras’ focus adjustments:

In [ ]:
camera1 = torch.tensor([[1, 2], [3, 4]])
camera2 = torch.tensor([[5, 6], [7, 8]])

In [ ]:
#1 Perform an element-wise multiplication of matrices ( Hadamard Product)
elementwise_product = camera1 * camera2
print(elementwise_product)

tensor([[ 5, 12],
        [21, 32]])


In [ ]:
#2 Compute Dot Product of the two matrices
dot_product = torch.matmul(camera1, camera2)
print(dot_product)

tensor([[19, 22],
        [43, 50]])


In [ ]:
#3 Compute the Determinant of each matrix
det_camera1 = torch.det(camera1.float())
det_camera2 = torch.det(camera2.float())
print(det_camera1)
print(det_camera2)

tensor(-2.)
tensor(-2.0000)


**KEY INSIGHTS**:

* Use **torch.matmul()** for matrix multiplication and "*" for element-wise multiplication.
* Determinants work only on square matrices.



---



**Task6: Neural Network Foundations**

Our AI University uses simplified single neuron model (perceptron):
$$y = wx + b$$

In [ ]:
#1 Create tensors for w  = 2, b = 1, x = [1, 2, 3, 4]
w = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)

x = torch.tensor([1, 2, 3, 4])
print(w)
print(b)
print(x)

tensor(2., requires_grad=True)
tensor(1., requires_grad=True)
tensor([1, 2, 3, 4])


In [ ]:
#2 Compute tensors for y
y = w * x + b
print(y)

tensor([3., 5., 7., 9.], grad_fn=<AddBackward0>)


PyTorch tracks gradients for all **requires_grad=True** tensors.



---

