<h2 align="center">Activation Functions</h2>

In [2]:
import numpy as np

### Sigmoid

In [5]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

values = np.array([-2, -1, 0, 1, 2, 10, 50, 500])
sigmoid(values)

array([0.11920292, 0.26894142, 0.5       , 0.73105858, 0.88079708,
       0.9999546 , 1.        , 1.        ])

### Softmax

In [9]:
def softmax(x):
    exp_x = np.exp(x - np.max(x))  # Subtracting max for numerical stability
    return exp_x / exp_x.sum(axis=0)

values = np.array([3, 8, 9, 7])
softmax(values)

array([0.00164625, 0.24432559, 0.6641458 , 0.08988236])

In [14]:
sum([0.00164625, 0.24432559, 0.6641458 , 0.08988236])

1.0

### Tanh

In [10]:
def tanh(x):
    return np.tanh(x)

In [11]:
values = np.array([-2, -1, 0, 1, 2, 10, 50, 500])
tanh(values)

array([-0.96402758, -0.76159416,  0.        ,  0.76159416,  0.96402758,
        1.        ,  1.        ,  1.        ])

### ReLU

In [13]:
def relu(x):
    return np.maximum(0, x)

values = np.array([-12, -8, 0, 7, 9, 100])
relu(values)

array([  0,   0,   0,   7,   9, 100])